builds:
  -
    binary: supervisord_static
    goos:
      - linux
      #- darwin
    goarch:
      - amd64
      - arm
    ldflags:
    - "-linkmode external -extldflags -static"
  -
    binary: supervisord
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
archive:
  format: binary
snapshot:
  name_template: "{{.Commit}}"
