builds:
  -
    id: "supervisord_static"
    binary: supervisord_static
    goos:
      - linux
#      - darwin
    goarch:
#      - amd64
      - arm
    goarm:
      - 7
    ldflags:
    - "-linkmode external -extldflags -static"
  -
    id: "supervisord"
    binary: supervisord
    goos:
      - linux
#      - darwin
    goarch:
#      - amd64
      - arm
    goarm:
      - 7
archive:
  format: binary
snapshot:
  name_template: "{{.Commit}}"
