# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# File "copiato" da: https://raw.githubusercontent.com/mailchain/mailchain/master/.goreleaser.yml

env:
- GO111MODULE=on
before:
  hooks:
    - go mod download
    # - go install github.com/golang/mock/mockgen
    # - go generate ./...
builds:
- id: supervisord-darwin-amd64
#  ldflags: -s -w -X github.com/mailchain/mailchain.Version={{.Version}} -X github.com/mailchain/mailchain.BuildDate={{.Date}} -X github.com/mailchain/mailchain.CommitHash={{ .ShortCommit }}
  binary: supervisord
  env:
  - CGO_ENABLED=1  
  - CC=o64-clang 
  - CXX=o64-clang++
  main: ./main.go 
  goos:
    - darwin
  goarch:
    - amd64

- id: supervisord-linux-amd64
#  ldflags: -s -w -X github.com/mailchain/mailchain.Version={{.Version}} -X github.com/mailchain/mailchain.BuildDate={{.Date}} -X github.com/mailchain/mailchain.CommitHash={{ .ShortCommit }}
  binary: supervisord
  env:
  - CGO_ENABLED=1
  main: ./main.go
  goos:
    - linux
  goarch:
    - amd64    

- id: supervisord-windows-amd64
#  ldflags: -s -w -X github.com/mailchain/mailchain.Version={{.Version}} -X github.com/mailchain/mailchain.BuildDate={{.Date}} -X github.com/mailchain/mailchain.CommitHash={{ .ShortCommit }}
  binary: supervisord
  env:
    - CGO_ENABLED=1
    - CC=x86_64-w64-mingw32-gcc
    - CXX=x86_64-w64-mingw32-g++
  main: ./main.go
  goos:
    - windows
  goarch:
    - amd64

archives:
- format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.ProjectName}}-v{{.Version}}-{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
    dragonfly: DragonFlyBSD
  files:
  - Readme.MD
  - LICENSE   
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
